### ISSUE TITLE
Changing any slider menu value moves the cursor to the center of the window

### ISSUE THREAD

**Issue by juizoi** [techartorg/bqt#69] opened 2023-05-04 09:43 UTC
After maximising the Blender Qt window, any changes I make to any slider in Blender's UI moves the cursor to the center.

**Comment by hannesdelbeke** [comment] 2023-05-04 10:13
Thank you for reporting this issue.

could you describe how you maximise the window?
asking since there are 2 ways to do so, 1 is not yet supported. see https://github.com/techartorg/bqt/issues/3

**Comment by juizoi** [comment] 2023-05-04 10:48
I use a setWindowState(QtCore.Qt.WindowMaximized) in the create_global_app method. had to do this since the app was starting in a small window.

**Comment by hannesdelbeke** [comment] 2023-05-30 21:48
Can you repro this without changing the source code for bqt?
if so can you share the code you run.

**Comment by hannesdelbeke** [comment] 2023-05-30 21:49
FYI, window might be small first time you start it.
but if you make it bigger, and restart blender. it should remember the last size and position it had.
so might be only an issue the first time you start blender

**Comment by hannesdelbeke** [comment] 2023-05-30 21:53
created a new issue for first time blender window wrap is too small https://github.com/techartorg/bqt/issues/72

this thread can focus on the problem of mouse resets to center if maximised

**Comment by hannesdelbeke** [comment] 2023-06-06 14:51
current workaround: disable qt wrapping with BQT_DISABLE_WRAP set to 1

**Comment by hannesdelbeke** [comment] 2023-06-06 20:43
afraid I can't repro this with the test code i created, 
hopefully this is now fixed. If not, feel free to reopen this.
It be great to add some repro code, that anyone can run. in Blender, to reproduce the issue

**Closed by hannesdelbeke** 2023-06-06 20:43 UTC
Labels: bug

**Comment by atticus-lv** [comment] 2023-07-23 05:26
#109 I can reproduce this problem

**Comment by atticus-lv** [comment] 2023-07-23 05:29
if the only method to fix it is set BQT_DISABLE_WRAP to 1, is there a solution to let the qt widgets to hide and show when the blender window is focus or not?

**Comment by hannesdelbeke** [comment] 2023-07-23 09:59
> if the only method to fix it is set BQT_DISABLE_WRAP to 1, is there a solution to let the qt widgets to hide and show when the blender window is focus or not?

if BQT_DISABLE_WRAP is 1, it should automatically handle widgets in foreground if blender is in focus.
to disable this behaviour you can set BQT_MANAGE_FOREGROUND to 0
