### ISSUE TITLE
Enabling QT will affect the capture of UI controls

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [techartorg/bqt#105] opened 2023-07-07 01:37 UTC
You cannot select multiple numeric boxes to edit at the same time

![image](https://github.com/techartorg/bqt/assets/65578116/d984b41d-3c97-4c42-b5c9-f6f774efd549)

**Comment by hannesdelbeke** [comment] 2023-07-15 14:46
Thanks you for reporting these 2 bugs.

Do you have more instructions on how to test the select multiple numeric boxes bug? I am not familiar with how to do this.

**Comment by hannesdelbeke** [comment] 2023-07-15 14:49
Can we also move the window content distortion bug to a separate thread? This makes it easier to keep the discussion focused.

**Comment by BUGProtectionAssociation** [comment] 2023-07-15 15:29
> Thanks you for reporting these 2 bugs.
> 
> Do you have more instructions on how to test the select multiple numeric boxes bug? I am not familiar with how to do this.

I couldn't set the values of Input box more than one by once step if I enable qt addon. Iikes the xyz  rgb hsv

**Comment by BUGProtectionAssociation** [comment] 2023-07-17 09:33
> ok just foun out how to do it. so in normal blender you can click and hold the x cell. then drag down yhe mouse cursor over Y and Z cell, and it will select all 3 cells and make them active.
> 
> however when testing this in bqt blender, this still seems to work for me. and i am able to edit multiple cells at the same time.
> 
> can you give me more info on your problem and how to test it?

When you open a new sub window or switch between other apps. Some keys fail, such as Alt Ctrl. When you select a control, it automatically refreshes and you lose focus on that control. If you want to continue editing, you need to click on that control again.
Sometimes normal, sometimes strange automatic refresh of UI content, resulting in loss of control focus and need to be reactivated with the mouse

**Comment by hannesdelbeke** [comment] 2023-07-17 10:04
aha, that is a duplicate of this bug then 
- https://github.com/techartorg/bqt/issues/60 

i'll close this issue and will follow up in there

**Closed by hannesdelbeke** 2023-07-17 10:04 UTC
